# all services
# version: '3.8'

services:
  auth-service:
    build: ./users
    container_name: auth-service
    ports:
      - "8000:8000"
    depends_on:
      - auth_db
    environment:
      DB_NAME: trello_auth
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_HOST: auth_db
      DB_PORT: 5432

  auth_db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: trello_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
